// src/components/panels/UserList.tsx
'use client';

import { useState, useMemo, useRef, useEffect, useCallback } from 'react';
import { useStore } from '@/stores';
import { nickColor } from '@/lib/nickcolor';
import type { WeeChatNick } from '@/types';

const TIER_ORDER = ['Owner', 'Admin', 'Op', 'Halfop', 'Voice', 'Regular'];

const TIER_ICONS: Record<string, { icon: string; label: string }> = {
  'Owner': { icon: '👑', label: 'Owner' },
  'Admin': { icon: '⚡', label: 'Admin' },
  'Op': { icon: '🛡️', label: 'Op' },
  'Halfop': { icon: '🔰', label: 'Half-Op' },
  'Voice': { icon: '🎙️', label: 'Voice' },
  'Regular': { icon: '', label: 'Regular' },
};

const TIER_SIGILS: Record<string, string> = {
  'Owner': '~', 'Admin': '&', 'Op': '@', 'Halfop': '%', 'Voice': '+', 'Regular': '',
};

interface Props {
  mobile?: boolean;
  onClose?: () => void;
}

interface NickAction {
  nick: string;
  x: number;
  y: number;
}

export default function UserList({ mobile, onClose }: Props) {
  const activeBuffer = useStore(s => s.activeBuffer);
  const buffers = useStore(s => s.buffers);
  const openQuery = useStore(s => s.openQuery);
  const sendInput = useStore(s => s.sendInput);
  const startCall = useStore(s => s.startCall);
  const colorNicks = useStore(s => s.settings.colorNicks);
  const enableVideoCalls = useStore(s => s.settings.enableVideoCalls);
  const callState = useStore(s => s.callState);
  const isOper = useStore(s => s.isOper);

  const [filter, setFilter] = useState('');
  const [collapsedGroups, setCollapsedGroups] = useState<Set<string>>(new Set());
  const [actionPopup, setActionPopup] = useState<NickAction | null>(null);
  const popupRef = useRef<HTMLDivElement>(null);
  const filterRef = useRef<HTMLInputElement>(null);

  const entry = activeBuffer ? buffers.get(activeBuffer) : null;
  const nickGroups = entry?.nickGroups ?? new Map();
  const totalNicks = entry?.nicks ? [...entry.nicks.values()].filter(n => !n.group && n.visible).length : 0;

  const filteredGroups = useMemo(() => {
    const fq = filter.trim().toLowerCase();
    const result = new Map<string, WeeChatNick[]>();
    for (const tier of TIER_ORDER) {
      const nicks = nickGroups.get(tier);
      if (!nicks) continue;
      const filtered = fq
        ? nicks.filter((n: WeeChatNick) => n.name.toLowerCase().includes(fq))
        : nicks;
      if (filtered.length > 0) {
        result.set(tier, filtered);
      }
    }
    for (const [label, nicks] of nickGroups) {
      if (TIER_ORDER.includes(label)) continue;
      const filtered = fq
        ? nicks.filter((n: WeeChatNick) => n.name.toLowerCase().includes(fq))
        : nicks;
      if (filtered.length > 0) {
        result.set(label, filtered);
      }
    }
    return result;
  }, [nickGroups, filter]);

  const toggleGroup = (label: string) => {
    setCollapsedGroups(prev => {
      const next = new Set(prev);
      if (next.has(label)) next.delete(label); else next.add(label);
      return next;
    });
  };

  useEffect(() => {
    if (!actionPopup) return;
    function onClick(e: MouseEvent) {
      if (popupRef.current && !popupRef.current.contains(e.target as Node)) {
        setActionPopup(null);
      }
    }
    document.addEventListener('mousedown', onClick);
    document.addEventListener('touchstart', onClick as EventListener);
    return () => {
      document.removeEventListener('mousedown', onClick);
      document.removeEventListener('touchstart', onClick as EventListener);
    };
  }, [actionPopup]);

  const handleNickClick = useCallback((nick: string, e: React.MouseEvent) => {
    const rect = (e.currentTarget as HTMLElement).getBoundingClientRect();
    setActionPopup({
      nick,
      x: mobile ? rect.left : rect.right + 4,
      y: rect.top,
    });
  }, [mobile]);

  const doAction = useCallback((action: string) => {
    if (!actionPopup) return;
    const { nick } = actionPopup;
    setActionPopup(null);
    switch (action) {
      case 'query': openQuery(nick); onClose?.(); break;
      case 'whois': sendInput(`/whois ${nick}`); break;
      case 'video': startCall(nick, true); onClose?.(); break;
      case 'voice': startCall(nick, false); onClose?.(); break;
      case 'kick': sendInput(`/kick ${nick}`); break;
      case 'ban': sendInput(`/ban ${nick}`); break;
    }
  }, [actionPopup, openQuery, sendInput, onClose, startCall]);

  if (!entry) return null;

  const tierColorForNick = (nick: WeeChatNick): string | undefined => {
    for (const [label, nicks] of nickGroups) {
      if (nicks.includes(nick) && label !== 'Regular') {
        return tierAccent(label);
      }
    }
    return undefined;
  };

  return (
    <aside className={`${mobile ? 'w-full' : 'w-[220px]'} shrink-0 flex flex-col h-full border-l border-white/[0.04] bg-gray-950 relative`}>
      {/* Header */}
      <div className="flex items-center h-11 sm:h-12 px-3 sm:px-3 border-b border-white/[0.04] shrink-0"
        style={mobile ? { paddingTop: 'env(safe-area-inset-top)' } : undefined}>
        <div className="flex items-center gap-2 flex-1 min-w-0">
          <svg className="w-4 h-4 sm:w-3.5 sm:h-3.5 text-[var(--custom-accent,#818cf8)] shrink-0" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round">
            <circle cx="6" cy="5" r="3" /><circle cx="11" cy="6" r="2.5" /><path d="M1 14c0-3 2-4.5 5-4.5" /><path d="M9 14c0-2.5 1.5-3.5 4-3.5" />
          </svg>
          <span className="text-[13px] sm:text-[12px] font-semibold text-gray-200 truncate">Users</span>
        </div>
        <span className="text-[11px] sm:text-[10px] font-mono tabular-nums px-1.5 py-0.5 rounded-md bg-white/[0.04] text-[var(--custom-accent,#818cf8)]">{totalNicks}</span>
        {mobile && onClose && (
          <button onClick={onClose} className="w-10 h-10 flex items-center justify-center rounded-xl text-gray-500 hover:text-gray-200 active:bg-white/[0.06] -mr-1 ml-1"
            aria-label="Close">
            <svg className="w-[18px] h-[18px]" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
              <path d="M4 4l8 8M12 4l-8 8" />
            </svg>
          </button>
        )}
      </div>

      {/* Search */}
      <div className="px-2 sm:px-2 pt-2 pb-1 shrink-0">
        <div className="relative">
          <svg className="absolute left-2.5 sm:left-2 top-1/2 -translate-y-1/2 w-3.5 h-3.5 sm:w-3 sm:h-3 text-gray-600 pointer-events-none" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
            <circle cx="6.5" cy="6.5" r="4.5" /><path d="M10 10l4 4" />
          </svg>
          <input ref={filterRef} type="text" value={filter} onChange={e => setFilter(e.target.value)}
            placeholder="Search users..."
            autoComplete="off" spellCheck={false}
            onKeyDown={e => { if (e.key === 'Escape') { setFilter(''); filterRef.current?.blur(); } }}
            className="w-full bg-white/[0.03] border border-white/[0.06] rounded-lg text-[13px] sm:text-[11px] text-gray-300 placeholder-gray-600 pl-8 sm:pl-7 pr-3 py-2 sm:py-1.5 outline-none focus:border-[var(--custom-accent,#818cf8)]/30 focus:bg-white/[0.04] transition-all" />
          {filter && (
            <button onClick={() => { setFilter(''); filterRef.current?.focus(); }}
              className="absolute right-2 top-1/2 -translate-y-1/2 w-5 h-5 flex items-center justify-center rounded text-gray-600 hover:text-gray-300 transition-colors">
              <svg className="w-3 h-3" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round">
                <path d="M4 4l8 8M12 4l-8 8" />
              </svg>
            </button>
          )}
        </div>
      </div>

      {/* Nick list */}
      <div className="flex-1 overflow-y-auto px-1.5 sm:px-1 pt-1 pb-2 nicklist-scroll">
        {Array.from(filteredGroups).map(([label, nicks]) => {
          const isCollapsed = collapsedGroups.has(label);
          const accent = tierAccent(label);
          const sigil = TIER_SIGILS[label] ?? '';
          const tierInfo = TIER_ICONS[label];

          return (
            <div key={label} className="mb-1">
              {/* Group header */}
              <button onClick={() => toggleGroup(label)}
                className="w-full flex items-center gap-1.5 px-2 py-2 sm:py-1.5 rounded-lg text-gray-500 hover:text-gray-300 hover:bg-white/[0.02] active:bg-white/[0.04] transition-all group">
                <svg className={`w-[9px] h-[9px] sm:w-[8px] sm:h-[8px] shrink-0 transition-transform duration-150 ${isCollapsed ? '-rotate-90' : ''}`}
                  style={{ color: accent }}
                  viewBox="0 0 8 8" fill="currentColor"><path d="M1 2l3 3.5L7 2z" /></svg>
                {tierInfo?.icon && <span className="text-[10px] sm:text-[9px] leading-none">{tierInfo.icon}</span>}
                <span className="text-[11px] sm:text-[10px] font-bold uppercase tracking-[0.08em] flex-1 text-left"
                  style={{ color: accent }}>
                  {label}
                </span>
                <span className="text-[10px] sm:text-[9px] tabular-nums font-mono px-1.5 py-0.5 rounded bg-white/[0.03] text-gray-500 group-hover:text-gray-400 transition-colors">
                  {nicks.length}
                </span>
              </button>

              {/* Nick entries */}
              {!isCollapsed && (
                <div className="ml-1 sm:ml-0.5 border-l border-white/[0.03] pl-1 sm:pl-0.5">
                  {nicks.map((nick: WeeChatNick) => {
                    const isActive = actionPopup?.nick === nick.name;
                    const color = colorNicks ? nickColor(nick.name) : undefined;
                    const initials = nick.name.slice(0, 2).toUpperCase();

                    return (
                      <button key={nick.name} onClick={e => handleNickClick(nick.name, e)}
                        className={`w-full flex items-center gap-2 sm:gap-1.5 px-1.5 sm:px-1 py-1.5 sm:py-[4px] rounded-lg sm:rounded-md text-[14px] sm:text-[12px] transition-all
                          ${isActive
                            ? 'bg-[var(--custom-accent,#818cf8)]/[0.08] text-gray-100'
                            : 'text-gray-400 hover:bg-white/[0.03] hover:text-gray-200 active:bg-white/[0.06]'}`}
                        title={nick.name}>
                        {/* Avatar */}
                        <div className="w-7 h-7 sm:w-5 sm:h-5 rounded-full flex items-center justify-center shrink-0 text-[9px] sm:text-[7px] font-bold relative"
                          style={{
                            background: color ? `${color}18` : 'rgba(255,255,255,0.04)',
                            color: color || 'var(--custom-accent, #818cf8)',
                          }}>
                          {initials}
                          {/* Tier badge */}
                          {sigil && (
                            <span className="absolute -top-0.5 -right-0.5 w-3 h-3 sm:w-2.5 sm:h-2.5 rounded-full flex items-center justify-center text-[7px] sm:text-[6px] font-bold leading-none"
                              style={{ background: accent, color: '#000' }}>
                              {sigil}
                            </span>
                          )}
                        </div>
                        {/* Name */}
                        <span className="truncate flex-1 text-left leading-tight"
                          style={color ? { color } : undefined}>
                          {nick.name}
                        </span>
                      </button>
                    );
                  })}
                </div>
              )}
            </div>
          );
        })}

        {filteredGroups.size === 0 && (
          <div className="flex flex-col items-center justify-center py-8 gap-2">
            <svg className="w-8 h-8 text-gray-700" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1" strokeLinecap="round">
              <circle cx="8" cy="5" r="3" /><path d="M2 14c0-3 3-5 6-5s6 2 6 5" />
            </svg>
            <span className="text-[11px] text-gray-600">
              {filter ? 'No matches' : 'No users'}
            </span>
          </div>
        )}
      </div>

      {/* Nick action popup */}
      {actionPopup && (
        <div ref={popupRef}
          className="fixed z-[100] animate-fade-up"
          style={{
            left: mobile ? '50%' : `${actionPopup.x}px`,
            top: `${Math.min(actionPopup.y, window.innerHeight - 260)}px`,
            transform: mobile ? 'translateX(-50%)' : undefined,
          }}>
          <div className="bg-gray-900 border border-white/[0.1] rounded-2xl shadow-2xl overflow-hidden min-w-[180px] backdrop-blur-sm"
            style={{ boxShadow: '0 8px 32px rgba(0,0,0,0.4), 0 0 0 1px rgba(255,255,255,0.04)' }}>
            {/* Popup header with avatar */}
            <div className="px-4 py-3 border-b border-white/[0.04] flex items-center gap-3">
              <div className="w-9 h-9 rounded-full flex items-center justify-center text-[11px] font-bold"
                style={{
                  background: `${nickColor(actionPopup.nick)}20`,
                  color: nickColor(actionPopup.nick),
                  boxShadow: `0 0 12px ${nickColor(actionPopup.nick)}15`,
                }}>
                {actionPopup.nick.slice(0, 2).toUpperCase()}
              </div>
              <div className="flex-1 min-w-0">
                <div className="text-[13px] font-semibold text-gray-100 truncate">{actionPopup.nick}</div>
                <div className="text-[10px] text-gray-500">
                  {(() => {
                    for (const [label] of nickGroups) {
                      const nicks = nickGroups.get(label);
                      if (nicks?.some((n: WeeChatNick) => n.name === actionPopup.nick) && label !== 'Regular') {
                        return label;
                      }
                    }
                    return 'User';
                  })()}
                </div>
              </div>
            </div>
            <div className="py-1.5">
              <PopupBtn icon="msg" label="Message" onClick={() => doAction('query')} />
              <PopupBtn icon="whois" label="Whois" onClick={() => doAction('whois')} />
              {enableVideoCalls && callState === 'idle' && (
                <>
                  <div className="h-px bg-white/[0.04] mx-3 my-1" />
                  <PopupBtn icon="video" label="Video Call" onClick={() => doAction('video')} accent="emerald" />
                  <PopupBtn icon="voice" label="Voice Call" onClick={() => doAction('voice')} accent="indigo" />
                </>
              )}
              {isOper && (
                <>
                  <div className="h-px bg-white/[0.04] mx-3 my-1" />
                  <PopupBtn icon="kick" label="Kick" onClick={() => doAction('kick')} danger />
                  <PopupBtn icon="ban" label="Ban" onClick={() => doAction('ban')} danger />
                </>
              )}
            </div>
          </div>
        </div>
      )}

      <style>{`
        .nicklist-scroll::-webkit-scrollbar { width: 4px; }
        .nicklist-scroll::-webkit-scrollbar-track { background: transparent; }
        .nicklist-scroll::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.06); border-radius: 2px; }
        .nicklist-scroll::-webkit-scrollbar-thumb:hover { background: rgba(255,255,255,0.12); }
      `}</style>
    </aside>
  );
}

function tierAccent(label: string): string {
  switch (label) {
    case 'Owner': return '#f87171';
    case 'Admin': return '#c084fc';
    case 'Op': return '#4ade80';
    case 'Halfop': return '#60a5fa';
    case 'Voice': return '#fbbf24';
    default: return 'var(--custom-accent, #818cf8)';
  }
}

function PopupBtn({ icon, label, onClick, danger, accent }: { icon: string; label: string; onClick: () => void; danger?: boolean; accent?: string }) {
  const accentClass = accent === 'emerald' ? 'text-emerald-400' : accent === 'indigo' ? 'text-indigo-400' : '';
  return (
    <button onClick={onClick}
      className={`w-full flex items-center gap-3 px-4 py-2.5 sm:py-2 text-[13px] sm:text-[12px] transition-all rounded-lg mx-0
        ${danger ? 'text-red-400 hover:bg-red-500/10 active:bg-red-500/15' : `${accentClass || 'text-gray-300'} hover:bg-white/[0.04] active:bg-white/[0.08]`}`}>
      <span className="w-4 h-4 flex items-center justify-center shrink-0">
        {icon === 'msg' && (
          <svg className="w-4 h-4" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round">
            <path d="M2 3h12v8H5l-3 3V3z" />
          </svg>
        )}
        {icon === 'whois' && (
          <svg className="w-4 h-4" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round">
            <circle cx="8" cy="5" r="3" /><path d="M3 14c0-3 2-5 5-5s5 2 5 5" />
          </svg>
        )}
        {icon === 'kick' && (
          <svg className="w-4 h-4" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round">
            <path d="M2 14l6-6m0 0L14 2M8 8l6 6M8 8L2 2" />
          </svg>
        )}
        {icon === 'video' && (
          <svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
            <rect x="2" y="5" width="15" height="14" rx="2" /><path d="M17 9l5-3v12l-5-3" />
          </svg>
        )}
        {icon === 'voice' && (
          <svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
            <rect x="9" y="2" width="6" height="11" rx="3" /><path d="M5 10a7 7 0 0014 0" /><path d="M12 17v4M8 21h8" />
          </svg>
        )}
        {icon === 'ban' && (
          <svg className="w-4 h-4" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5">
            <circle cx="8" cy="8" r="6" /><path d="M3.5 3.5l9 9" strokeLinecap="round" />
          </svg>
        )}
      </span>
      {label}
    </button>
  );
}

// src/lib/components/UserList.svelte
<script lang="ts">
  import { buffers } from '$lib/stores/buffers.svelte.js';
  import { chat } from '$lib/stores/chat.svelte.js';
  import { nickColor } from '$lib/utils/nickcolor.js';
  import { settings } from '$lib/stores/settings.svelte.js';
  import type { WeeChatNick } from '$lib/weechat/types.js';
  import { video } from '$lib/stores/video.svelte.js';

  const entry = $derived(buffers.active ? buffers.buffers.get(buffers.active) : null);

  // Fetch nicklist whenever we switch to a new buffer
  let lastFetched = $state<string | null>(null);
  $effect(() => {
    const ptr = buffers.active;
    if (ptr && ptr !== lastFetched) {
      lastFetched = ptr;
      chat.requestNicklist(ptr);
    }
  });

  let filter = $state('');
  let collapsedGroups = $state<Set<string>>(new Set());
  let popover = $state<{ nick: WeeChatNick; x: number; y: number } | null>(null);

  const nickGroups = $derived(entry?.nickGroups ?? new Map<string, WeeChatNick[]>());

  function toggleGroup(groupName: string) {
    const next = new Set(collapsedGroups);
    if (next.has(groupName)) {
      next.delete(groupName);
    } else {
      next.add(groupName);
    }
    collapsedGroups = next;
  }

  function filterNicks(nicks: WeeChatNick[]): WeeChatNick[] {
    if (!filter) return nicks;
    const lc = filter.toLowerCase();
    return nicks.filter(n => n.name.toLowerCase().includes(lc));
  }

  function openPopover(e: MouseEvent, nick: WeeChatNick) {
    e.stopPropagation();
    const x = Math.min(e.clientX, window.innerWidth - 240);
    const y = Math.min(e.clientY, window.innerHeight - 200);
    popover = { nick, x, y };
  }

  function closePopover() {
    popover = null;
  }

  function nickStyle(name: string): string {
    if (!settings.colorNicks) return '';
    return `color: ${nickColor(name)}`;
  }

  // Map WeeChat color name or numeric string to a CSS color string
  const WEECHAT_NAMED: Record<string, string> = {
    black: '#000', red: '#cc2222', green: '#22aa44', brown: '#aa7700',
    yellow: '#ccaa00', blue: '#3355cc', magenta: '#aa44aa', cyan: '#228899',
    white: '#ddd', lightgray: '#bbb', darkgray: '#777',
    lightred: '#ff5555', lightgreen: '#44ee66', lightyellow: '#ffff44',
    lightblue: '#5577ff', lightmagenta: '#ff66ff', lightcyan: '#44ddff',
    default: '',
  };
  // xterm-256 cube (same logic as formatter.ts buildExtended)
  function xtermColor(n: number): string {
    if (n < 0 || n > 255) return '';
    if (n < 16) {
      const base16 = ['#000','#800','#080','#880','#008','#808','#088','#ccc',
                      '#888','#f55','#5f5','#ff5','#55f','#f5f','#5ff','#fff'];
      return base16[n] ?? '';
    }
    if (n < 232) {
      const i = n - 16, bv = i % 6, gv = Math.floor(i / 6) % 6, rv = Math.floor(i / 36);
      const c = (v: number) => v === 0 ? 0 : 55 + v * 40;
      return `rgb(${c(rv)},${c(gv)},${c(bv)})`;
    }
    const v = 8 + (n - 232) * 10;
    return `rgb(${v},${v},${v})`;
  }
  function weechatColor(spec: string): string {
    if (!spec) return '';
    const named = WEECHAT_NAMED[spec.toLowerCase()];
    if (named !== undefined) return named;
    const n = parseInt(spec, 10);
    if (!isNaN(n)) return xtermColor(n);
    return '';
  }

  function prefixStyle(nick: WeeChatNick): string {
    const css = weechatColor(nick.prefixColor);
    return css ? `color: ${css}` : '';
  }

  // Count total non-group nicks
  const totalNicks = $derived(() => {
    let n = 0;
    for (const [, nicks] of nickGroups) n += nicks.length;
    return n;
  });
</script>

<!-- svelte-ignore a11y_no_static_element_interactions a11y_no_noninteractive_element_interactions -->
<aside
  aria-label="User list"
  class="flex flex-col h-full bg-gray-900 border-l border-gray-800"
  style="width: 220px; flex-shrink: 0;"
  onclick={closePopover}
  onkeydown={(e) => e.key === 'Escape' && closePopover()}
>
  <!-- Header -->
  <div class="px-3 py-2.5 border-b border-gray-800 flex-shrink-0">
    <div class="flex items-center justify-between mb-2">
      <span class="text-xs font-semibold text-gray-400 uppercase tracking-widest">Users</span>
      <span class="text-xs text-gray-600">{totalNicks()}</span>
    </div>
    <input
      class="w-full bg-gray-800 border border-gray-700 rounded text-xs text-gray-300 px-2 py-1 outline-none focus:border-blue-500 placeholder-gray-600"
      bind:value={filter}
      placeholder="Filter users…"
      autocomplete="off"
      spellcheck="false"
    />
  </div>

  <!-- Nick groups -->
  <div class="flex-1 overflow-y-auto py-1">
    {#if !entry}
      <div class="px-3 py-4 text-xs text-gray-600 text-center">No channel selected</div>
    {:else if nickGroups.size === 0}
      <div class="px-3 py-4 text-xs text-gray-600 text-center">No users</div>
    {:else}
      {#each nickGroups as [groupName, nicks] (groupName)}
        {@const visible = filterNicks(nicks)}
        {#if visible.length > 0}
          <!-- Group header -->
          <button
            class="w-full text-left px-3 py-1 flex items-center justify-between group transition-colors hover:bg-gray-800/40"
            onclick={() => toggleGroup(groupName)}
          >
            <span class="text-[10px] font-bold uppercase tracking-widest text-gray-500 group-hover:text-gray-400 transition-colors">
              {groupName}
            </span>
            <span class="flex items-center gap-1">
              <span class="text-[10px] text-gray-600">{visible.length}</span>
              <svg
                class="w-2.5 h-2.5 text-gray-600 transition-transform {collapsedGroups.has(groupName) ? '-rotate-90' : ''}"
                viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
              >
                <path d="M4 6l4 4 4-4"/>
              </svg>
            </span>
          </button>

          {#if !collapsedGroups.has(groupName)}
            {#each visible as nick (nick.name)}
              <button
                class="w-full text-left px-3 py-0.5 flex items-center gap-1.5 text-xs transition-colors hover:bg-gray-800/60 group"
                onclick={(e) => openPopover(e, nick)}
              >
                {#if settings.showPrefixes && nick.prefix.trim()}
                  <span class="flex-shrink-0 font-mono text-[11px] font-bold w-3" style={prefixStyle(nick)}>{nick.prefix.trim()}</span>
                {:else}
                  <span class="w-3 flex-shrink-0"></span>
                {/if}
                <span
                  class="truncate flex-1 group-hover:brightness-125 transition-all {nick.visible === false ? 'opacity-40' : ''}"
                  style={nickStyle(nick.name)}
                >
                  {nick.name}
                </span>
              </button>
            {/each}
          {/if}
        {/if}
      {/each}
    {/if}
  </div>
</aside>

<!-- Nick popover -->
{#if popover}
  <div
    role="tooltip"
    class="fixed z-50 bg-gray-800 border border-gray-700 rounded shadow-xl py-2 px-3 text-xs text-gray-300 min-w-[180px]"
    style="left: {popover.x}px; top: {popover.y}px;"
    onclick={(e) => e.stopPropagation()}
    onkeydown={(e) => e.stopPropagation()}
  >
    <div class="font-semibold text-sm mb-1" style={nickStyle(popover.nick.name)}>{popover.nick.name}</div>
    {#if popover.nick.prefix.trim()}
      <div class="text-gray-500">Mode: {popover.nick.prefix.trim()}</div>
    {/if}
    <div class="mt-2 flex gap-2 flex-wrap">
      <button
        class="px-2 py-1 bg-gray-700 hover:bg-gray-600 rounded text-xs transition-colors"
        onclick={() => { window.dispatchEvent(new CustomEvent('insert-text', { detail: popover!.nick.name + ': ' })); closePopover(); }}
      >Mention</button>
      <button
        class="px-2 py-1 bg-gray-700 hover:bg-gray-600 rounded text-xs transition-colors"
        onclick={() => { chat.openQuery(popover!.nick.name); closePopover(); }}
      >Message</button>
      {#if settings.enableVideoCalls}
      <button
        class="px-2 py-1 bg-gray-700 hover:bg-gray-600 rounded text-xs transition-colors"
        onclick={() => { video.startCall(popover!.nick.name); closePopover(); }}
        title="Start video call"
      >📹 Call</button>
      {/if}
      <button
        class="px-2 py-1 bg-gray-700 hover:bg-gray-600 rounded text-xs transition-colors"
        onclick={() => { chat.sendInput(`/whois ${popover!.nick.name}`); closePopover(); }}
      >Whois</button>
    </div>
  </div>
{/if}
